@echo off
REM ###########################################################################
REM Script generated by HP Fortify SCA Scan Wizard (c) HP Fortify 2011
REM Created on 2012/09/21 15:50:57
REM ###########################################################################
REM Generated for the following languages:
REM 	Java
REM 	JSP J2EE
REM 	XML
REM ###########################################################################
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM BUILDID - the SCA build id
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM ARGFILE - the name of the argument file that's extracted and passed to SCA
REM MEMORY - the memory settings for SCA
REM OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="FortifySpringMVCSample1.fpr"
set BUILDID="SpringMVCSample1"
set ARGFILE="FortifySpringMVCSample1.bat.args"
set MEMORY=-Xmx1200M -Xms600M -Xss24M 
set LAUNCHERSWITCHES=""
set OLDFILENUMBER=FortifySpringMVCSample1.bat.fileno
set FILENOMAXDIFF=10

set PROJECTROOT0="C:\Java\workspaces\HelloWorldSpring3\SpringMVCSample1"
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >FortifySpringMVCSample1.bat.args
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
ENDLOCAL

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -scan -f %FPR%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\aopalliance-1.0.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\asm-4.0.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\asm-util-4.0.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\cglib-3.0.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\com.springsource.net.sf.cglib-2.2.0.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\com.springsource.org.aopalliance-1.0.0.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-fileupload-1.1.1.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-io-1.2.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\commons-logging-1.1.1.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\hibernate-validator-4.0.2.GA.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\jaxb-api.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\jaxb-impl.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\jstl-1.2.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\log4j-1.2.14.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\slf4j-api-1.5.6.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\slf4j-log4j12-1.5.6.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-aop-3.0.5.RELEASE.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-asm-3.0.3.RELEASE.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-beans-3.0.3.RELEASE.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-context-3.0.3.RELEASE.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-core-3.0.3.RELEASE.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-expression-3.0.3.RELEASE.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-web-3.0.3.RELEASE.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\spring-webmvc-3.0.3.RELEASE.jar;PROJECTROOT0_MARKER\WebContent\WEB-INF\lib\validation-api-1.0.0.GA.jar"
REM ARGS "-source"
REM ARGS "1.5"
REM ARGS -exclude "PROJECTROOT0_MARKER\.settings\org.eclipse.wst.common.project.facet.core.xml"
REM ARGS "PROJECTROOT0_MARKER"
